# Generated by Django 2.0.5 on 2018-05-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('time_reported', models.DateTimeField(null=True, verbose_name='Time Reported')),
                ('time_received', models.DateTimeField(db_index=True, null=True, verbose_name='Time Received')),
                ('host', models.CharField(max_length=32, null=True, verbose_name='From Host')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('tag', models.CharField(db_index=True, max_length=32, null=True, verbose_name='Syslog Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsyslog.Facility'),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsyslog.Priority'),
        ),
    ]
