# Generated by Django 2.0.5 on 2018-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsyslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=32, null=True, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='Program'),
        ),
    ]
