# Generated by Django 2.0.5 on 2018-05-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsyslog', '0002_auto_20180517_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsyslog.Facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsyslog.Priority', verbose_name='Severity'),
        ),
    ]
